.travis.yml

- MacOS buid started failing because of brew package changes.

Fix maxbuild

---

include/snowflake/logger.h
include/snowflake/platform.h
lib/arraylist.c
lib/client.c
lib/connection.c
lib/logger.c
lib/platform.c
tests/CMakeLists.txt
tests/test_logger.c

- Added CAPI version INFO to the log. This is consistent with the recent ODBC change.
- Fixed memory leak in sf_array_list when binding results. If the result buffer is not bound and the returned column is more than 8, fetch attempts to read uninitialized buffer.
- Added a function converting a debug level string to enum.

Fix logging

---

include/snowflake/client.h
lib/client.c
tests/CMakeLists.txt
tests/data/.gitignore
tests/test_adjust_fetch_data.c

This is an enhancement for PDO for Snowflake to fix:
https://github.com/snowflakedb/pdo_snowflake/issues/148
The problem is if multiple columns use STRING data type, and you fetch data, the size of buffers are allocated to the number of columns multiplied by 16MB, too much memory consumption.
It is due to the C API design, which enforces the applications to provider buffer before fetching data.
The fix is have `snowflake_fetch` function reallocate the memory if the given maximum buffer size is not large enough and return the new pointer. It is achieved by the statement attribute `SF_STMT_USER_REALLOC_FUNC` that is called.

Add realloc memory hook for fetching data

---

CMakeLists.txt
cpp/lib/Column.cpp
cpp/lib/Connection.cpp
cpp/lib/Exceptions.cpp
cpp/lib/Statement.cpp
include/snowflake/Column.hpp
include/snowflake/Connection.hpp
include/snowflake/Exceptions.hpp
include/snowflake/Param.hpp
include/snowflake/Statement.hpp
include/snowflake/client.h
lib/client.c
lib/results.c
lib/results.h
tests/CMakeLists.txt
tests/test_cpp_select1.cpp
tests/test_crud.c
tests/utils/TestSetup.cpp
tests/utils/TestSetup.hpp

Added basic C++ Wrapper API. An example of how the API works is shown in "test_cpp_select1.cpp". Updated SF_TYPE to SF_DB_TYPE to solve naming conflict with Windows.

C++ Wrapper API

---

lib/client.c
lib/connection.c
lib/platform.c
tests/CMakeLists.txt
tests/test_issue_76.c

Changed the regex string that does PUT/GET detection to reduce the number of false positives (queries that are labeled as PUT/GET queries but are not). Also fixed an issue where a query error would not get propagated to the user. Fixed some whitespace issues in connection.c

Fixed PUT/GET Detection

---

cpp/util/Base64.cpp
tests/test_unit_base64.cpp

I made a typo on the cpp style Base64 decode method, specifically:
https://github.com/snowflakedb/libsnowflakeclient/compare/jwt?expand=1#diff-a4b11b74cdecb4aa697704b9d3a549b4L75
This PR corrected it and added test cases to verify that.

Fix a Base64 Decode bug

---

include/snowflake/client.h
lib/client.c
tests/test_column_fetch.c

Implemented SF_TIMESTAMP type as well as associated timestamp creation and get functions. Updated existing code to use new SF_TIMESTAMP type. Added a function to transform a column into a timestamp type. Added test case to test all get functions.

Timestamp type

---

scripts/_init.sh
scripts/build_curl.sh
scripts/build_openssl.sh

Updated build scripts to take in a user specified version of GCC/GXX and to make sure that curl and openssl use the same version of GXX/GXX that the other libraries use.

Build with user specified version of GCC/GXX

---

cpp/StatementPutGet.cpp
include/snowflake/PutGetParseResponse.hpp

The parameter passed into the struct has the same name as member variable and caused a lot of warning thrown on the ODBC since it uses stricter compile flag. It would be a good chance to meet up with higher standard during the Simba upgrade this time.
Since the constructor seems to not being used anywhere, I just throw it away.

Remove constructor of EncryptionMaterial

---

scripts/build_cmocka.sh

I have to push this to unblock ODBC release.

disable cmocha test to mitigate flaky test results

---

cpp/FileCompressionType.cpp
tests/test_simple_put.cpp

We need case insensitive comparison here.

ODBC driver throws error with SOURCE_COMPRESSION = GZIP

---

cpp/FileTransferExecutionResult.cpp
cpp/SnowflakeS3Client.cpp
deps/curl-7.66.0/lib/vtls/sf_ocsp.c

1. Make consistent behavior for put command with overwrite=off
https://github.com/snowflakedb/libsnowflakeclient/issues/165
2. Fix security issue in curl/lib/vtls/sf_ocsp.c
http://cwe.mitre.org/data/definitions/134.html

Simba Changes

---

cpp/FileMetadataInitializer.cpp
cpp/FileTransferAgent.cpp
cpp/FileTransferAgent.hpp
cpp/FileTransferExecutionResult.cpp
cpp/FileTransferExecutionResult.hpp
cpp/SnowflakeAzureClient.cpp
cpp/SnowflakeS3Client.cpp
cpp/SnowflakeTransferException.cpp
cpp/crypto/CipherContext.cpp
cpp/crypto/CipherStreamBuf.cpp
cpp/jwt/Signer.cpp
cpp/util/Base64.hpp
cpp/util/ByteArrayStreamBuf.cpp
cpp/util/CompressionUtil.cpp
include/snowflake/ITransferResult.hpp
lib/chunk_downloader.c
lib/client.c
lib/memory.c

1. Add check for correct platform before compiler-specific pragmas.
`cpp/SnowflakeTransferException.cpp`
2. Remove deprecated alias setmode and use  _setmode instead.
`cpp/util/CompressionUtil.cpp`
3. Make various type casts/changes.

Fix Visual Studio level 3 compiler warnings

---

cpp/FileCompressionType.cpp
tests/test_unit_file_type_detect.cpp

When a file with no extension is uploaded, the driver tries to guess the file type compression and fails. 
This fixes the type and returns unknown so we handle it as a normal file.

SNOW-163154 Fixes auto compression guess

---

cpp/FileMetadataInitializer.cpp
include/snowflake/platform.h
tests/test_unit_file_metadata_init.cpp

On windows file path C:/Users/vreddy/TestData/testput.csv fails to upload.
This fix will address this issue.

SNOW-170115 ODBC put on windows fails when file paths have forward slash

---

deps/oob-1.0.2/jsonutil.c
deps/oob-1.0.2/jsonutil.h
deps/oob-1.0.2/oobtelemetry.h
tests/test_unit_oob.cpp

Sample payload:
`[{
"Created_On":	"2020-07-14 02:49:50",
"Name":	"SimbaIniConfig",
"SchemaVersion":	1,
"Tags":	{
"UUID":	"2648fde6-9193-42b3-9c6b-4788c70c0383",
"connectionString":	"snowflake.local.snowflakecomputing.com:443:/session/v1/login-request?requestId=c4d53986-ee7a-4f01-9fac-2604653e9c41&request_guid=abbab0e5-5c77-4102-9d29-d44efde6a050&databaseName=testdb&schemaName=testschema&warehouse=regress",
"ctx_account":	"sfctest0",
"ctx_port":	"443",
"ctx_protocol":	"https",
"ctx_user":	"snowman",
"driver":	"ODBC",
"version":	"99.0.0",
"hostOs":	"Linux",
"telemetryServerDeployment":	"dev"
},
"Type":	"Log",
"UUID":	"2648fde6-9193-42b3-9c6b-4788c70c0383",
"Urgent":	false,
"Value":	{
"DSN":	{
"server":	"snowflake.local.snowflakecomputing.com"
},
"Simba":	{
"DriverManagerEncoding":	"UTF-16", …

Add simba.ini info to oob

---

ci/build/build.sh
ci/build_linux.sh
ci/build_win.bat

I found the local build test doesn't detect inconsistency between dependencies and libsnowflakeclient.
This change is to clean up the dependency's staging area before running the build.
`BUILD_CLEAN` can be set to `false` if the download/build can be skipped for faster dev test iteration optionally.

add BUILD_CLEAN flag

---

include/snowflake/client.h
lib/client.c
lib/connection.c
tests/test_timestamp_ltz.c
tests/test_timestamp_ntz.c
tests/test_timestamp_tz.c

The current implementation is not dealing with TSs with precision 0 and considers them as malformed.
closing #221

Handling timestamps with zerp precision

---

include/snowflake/client.h
lib/client.c
tests/test_column_fetch.c

Description
@sfc-gh-kwagner this is change that I did for SNOW-81888 locally quite a while ago (in branch I created for stored proc) but fell through crack to be checked into the main repo

Using time_t instead of int 32 to avoid overflow SNOW-81888

---

include/snowflake/Statement.hpp
include/snowflake/client.h
lib/client.c
lib/results.c
lib/results.h
tests/CMakeLists.txt
tests/test_row_metadata.c

Description
The XP change that uses the row metadata parsed here can be found in this PR https://github.com/snowflakedb/snowflake/pull/9493
Note: The enclosed test (test_row_metadata) is commented out because the response changes that were made to GS have not yet been deployed at the time of this PR. The response change should be deployed in 4.28. Once 4.28 is deployed, I will enable the test. The JIRA to track enabling the test is https://snowflakecomputing.atlassian.net/browse/SNOW-180697
Here is a screenshot of the test passing on my local dev environment with the latest GS:
Testing
A test is enclosed

SNOW-57187 Parse row metadata from response in libsnowflakeclient

---

.gitignore
scripts/arrow.mk
scripts/build_arrow.sh

The initial version of the script is to add to the build script and make file to build Arrow and its dependencies. At this point any change in arrow version requires manual intervention as the arrow directory structure may change. And also requires testing the ODBC build with new libraries.

Add build scripts for arrow

---

cpp/logger/SFAwsLogger.cpp

This change can fix the test case failure for logging of put/get on GCP.

mask logging of sensitive information from AWS SDK

---

cpp/FileTransferAgent.cpp
cpp/FileTransferAgent.hpp
include/snowflake/IFileTransferAgent.hpp
tests/test_unit_put_retry.cpp

Adds the ability to configure the number of retries to perform when a put command fails.
Test case is added to test if the set number of retries are performed.

SNOW-219403 Add configurable retries for put fails

---

include/snowflake/client.h
lib/client.c

This is a change that we need for our use case in SQL stored procedures. 
Basically here is a short background on this change: Inside SQL stored procs (which are translated to JS stored procs) we will be evaluating expressions as much as we can on the XP side (through XP expression evaluation framework) instead of issuing an individual child job through LibSnowflakeClient. E.g. consider expression `'2020-10-10' + 1` which we can via two approaches, i.e., 1) either directly in XP or 2) or with a child query `SELECT '2020-10-10' + 1` through libSfClient where the result is extracted using `snowflake_column_as_str` as a string. But if this expression is evaluated on XP side we get the internal representation which is an epoch value (the same raw value representation in LibSfClient). So to …

Smirzaei get column string representation from raw value

---

include/snowflake/client.h
lib/client.c
lib/client_int.h
tests/test_arrow_force.c
tests/test_get_query_result_response.c

In SNOW-237995, and in PR #253, I modified SF_STMT to contain a field `query_response_text`, which used memory allocated by libsnowflakeclient.
This task is to track refactoring this code to instead use caller-managed memory via a new struct called SF_QUERY_RESPONSE_CAPTURE and a method `snowflake_execute_with_capture`.

SNOW-249762: Refactor Query-Result Capture

---

lib/client.c
tests/test_bind_named_params.c
tests/test_bind_params.c

This is for the issue reported for PHP driver https://github.com/snowflakedb/pdo_snowflake/issues/220
The root cause is that the new size is incorrect when growing the buffer for named parameters.
Add test cases for more than 8 named parameters and positional parameters as well.

Simba incident 00284803: crash with named parameters more than 8

---

lib/platform.c
tests/test_timestamp_ltz.c
tests/test_timestamp_ntz.c
tests/test_timestamp_tz.c

PHP driver is using libsnowflakeclient and negative epoch caused test case failures on Windows.
The implementation is taken from ODBC driver in Platform/DataConversion.cpp.

Add support for negative epoch on Windows.

---

lib/platform.c

simba incident 00294764: thread handle leak on Windows when using put/get command.

Fix thread handle leak on Windows

---

include/snowflake/logger.h
lib/client.c
lib/logger.c
tests/test_unit_logger.c

Simba incident 00295760: PHP driver creates empty log files.
Delay log file creation to when actual log output is needed.

Avoid empty log file generation.

---

include/snowflake/client.h
lib/client.c
tests/test_get_query_result_response.c

Previously we require the caller of `snowflake_execute_with_capture` to allocate memory for `result_capture->capture_buffer`. The initial motivation is to make it easy for xp to manage dynamically allocated memories. However, the draw back is that caller have no idea about how much memory should be allocated. 
This PR aims to refactor RESULT_CAPTURE to allocate response space in library. The memory is allocated in `snowflake_execute_with_capture` to variable `result_capture->capture_buffer`. Then the memory is freed in `snowflake_query_result_capture_term`.
We rely on caller following the pattern of calling `snowflake_query_result_capture_init` to init result_capture and calling `snowflake_query_result_capture_term` to free the memory.

SNOW-289058 Refactor RESULT_CAPTURE to allocate response space in-library

---

include/snowflake/client.h
lib/client.c
lib/client_int.h
lib/connection.c
lib/connection.h
tests/CMakeLists.txt
tests/test_get_describe_only_query_result.c

Currently libsnowflakeclient only support snowflake_execute, which will execute a snowflake statement. In JDBC, apart from statement.execute(), there is another API called statement.describe(), which will execute the query in describe only mode. Describe only means GS will only return some metadata associated with the sql, but won’t actually execute the query.
Statement.describe() is a key dependency for Java Stored Procedures, thus we want to add a new api in libsnowflakeclient, snowflake_describe, for Java SP.

SNOW-293305 Add describe only api

---

cpp/SnowflakeAzureClient.cpp
cpp/SnowflakeS3Client.cpp
tests/test_simple_put.cpp

Simba incident 00298808
When execute put command on AWS, having a subfolder in the stage and not ending it with / will cause failure.
example: put file://c:\puttest\data.tar.gz @stage/subfolder
In the case of Azure, the last charater of the subfolder name is truncated, so the file is uploaded to stage/subfulde
The reason is that the S3Client and AzureClient expect stage location end with /, while in the case of subfolder, it's not.

allow put to a subfolder without ending with /

---

cpp/FileTransferAgent.cpp
cpp/SnowflakeS3Client.cpp
include/snowflake/IFileTransferAgent.hpp
include/snowflake/platform.h
lib/platform.c
tests/test_simple_put.cpp

Simba incident 00306532.
Make temp directory configurable when initialize FileTransferAgent. Add user name to the default value as well.

Configurable temp directory

---

lib/client.c
tests/test_get_query_result_response.c

In XP, when the query we issued to GS failed, we want to propagate the error message to UDF server.
Currently in libsfclient, if the execution failed, we free the memory space where we store the GS response. This PR changed this behavior that even if GS returns a failed message, snowflake_execute_with_capture will always stores the response in the passed in result_capture struct. 
This won't cause memory leak, because caller will always call snowflake_result_capture_term to free the memory in result_capture struct.

SNOW-303289 Fix error in xp

---

cpp/SnowflakeAzureClient.cpp

Fix compilation errors on centos 7 / g++82 compiler toolchain to make it build for XP
And also for porting libnsnowflakeclient to run on ARM processors.

fix centos 7 compiler errors with sb_strcpy 

---

cpp/FileMetadataInitializer.hpp
cpp/SnowflakeS3Client.cpp
include/snowflake/IFileTransferAgent.hpp
tests/test_simple_put.cpp

When the parameter FORCE_REGIONAL_S3_ENDPOINTS_FOR_PRESIGNED_URLS is set to true then invoke a different API to generate S3 regional url.
This does NOT break any existing customers. The above parameter will be set true to private link parameters in the AWS us-east-1 regions.

AWS s3 private links now get regional URL when relevant parameter is set

---

lib/http_perform.c

With backoff mechanism, we should make sure to return error on timeout otherwise the query is silently skipped (SUCCESS is returned)
Description
Testing

Fixing the bug backoff mechanism

---

lib/client.c
tests/test_crud.c

DML query should return resultset and that was broken when adding arrow support. Fix it and add test case.
The test case passed on older version of 0.5.10 so the behavior should be the same as before.

Bug fix of arrow support: broken resultset of DML query

---

cpp/FileTransferAgent.hpp

The goal of this PR is to skip file retry if the file uploaded already exists in the Staging area.

Do not retry when the file already exists in the stage

---

cpp/logger/SFLogger.cpp

To improve performance, We want to skip log secret detector when running in XP mode.

snowflakeclient Disable secretDetection for XP

---

cpp/FileTransferAgent.cpp
cpp/util/CompressionUtil.cpp
cpp/util/CompressionUtil.hpp
include/snowflake/IFileTransferAgent.hpp
tests/test_simple_put.cpp

Fix for simba ticket 00316238. Make compress level configurable. Will make another PR on ODBC side when this PR is merged.

support configurable compress level

---

cpp/jwt/ClaimSet.hpp
lib/cJSON.c
lib/cJSON.h
lib/client.c
lib/connection.c

In rare occasions LibSfClient complains that the received response from GS does not contain query code (which is set null for success and the corresponding error code in case of failure). With this task we want to log response in such case

SNOW-366837 add log when query code miss

---

cpp/lib/ArrowChunkIterator.cpp

reflection from ODBC PR287 https://github.com/snowflakedb/snowflake-odbc/pull/287
Check result status before calling ValueOrDie() to avoid crash.
The comment in arrow's header file for ValueOrDie():
This method should only be called if this Result object's status is OK
(i.e. a call to ok() returns true), otherwise this call will abort.

Check result status before calling ValueOrDie()

---

lib/chunk_downloader.c
lib/connection.c
lib/connection.h
lib/http_perform.c
lib/logger.c
lib/mock_http_perform.h

Issue: Snowhouse has the limitation of the log message size. Therefore, we need to keep the useful information and delete inessential attributes in response json. 
On the other hand, I just check the original text if it exist the "code" attribute to triage the "miss code" issue happened in libsfclient or GS side.
Add a parameter to avoid string search for each query, I plan to continue using the previous parameter because the issue still happened in query execution step( which the parameter name is make sense). Also since we are roll out the port libsfclient to XP, I do not want to add too much temporary parameter. cc @sfc-gh-kwang Do you think we need to make the same change in your branch(XP part of libsfclient).

Simplify the log in response json

---

deps/curl-7.74.0/lib/vtls/sf_ocsp.c

Fix crash issue with OCSP reported by Simba's customer.
ocsp_log_data is freed inside generateOCSPTelemetryData() which still could be used outside in checkCertOCSP() for the next cert.

Fix crash issue with OCSP

---

ci/dev/CentOS-Base.repo
ci/dev/Dockerfile
ci/scripts/login_internal_docker.sh
cpp/SnowflakeS3Client.cpp
cpp/SnowflakeS3Client.hpp
cpp/StatementPutGet.cpp
include/snowflake/PutGetParseResponse.hpp
lib/client.c
lib/client_int.h
lib/connection.c
tests/CMakeLists.txt
tests/test_unit_put_get_fips.cpp

This change only affects PUT / GET functionality in Libsnowflakeclient and ODBC Driver. 
Till now the driver could only support default stage URLs or region based stage URLs. However while using Gov Cloud, there are certain security requirements that only few deployments and stages can adhere to at the moment. These stages / deployments are FIPS enabled. To ensure that the driver only connects to stages that are FIPS enabled, the GS would send to the driver exact URL that it needs to connect to. 
This fix updates the driver to accept the new information and use that instead of the default S3 URL.

Update for FIPS support

---

lib/connection.c
lib/http_perform.c

For this PR, I did two things:
1. Add log around the `curl_easy_perform` function because this is a function that may cause the query stuck in libsfclient, we should add log in advance so when the issue happens again, we could direct check it.
2. Delete some useless logs, it should be my fault, I made a small mistake in the curl_get_call and curl_post_call, the outside do while loop, the condition is while(0) so it will not cause an infinite loop here.
Next step:
I hope this is the last time to adjust the log in the third part of libsfclient. I will update the related log in XP's libsfclient

Adjust the log in libsfclient

---

CMakeLists.txt
cpp/util/SnowflakeCommon.cpp
include/snowflake/client.h
lib/client.c
lib/error.h
tests/test_unit_connect_parameters.c

Simba ticket 00349937. Allow user set the value for CLIENT_ENVIRONMENT::APPLICATION in the logging request via the 'application' connection setting. PHP connector is using libsnowflakeclient so we need the change here.

SNOW-395243 Support application in connection settings

---

deps/curl-7.78.0/lib/vtls/sf_ocsp.c
tests/unit_test_ocsp/CMakeLists.txt

The size of buffer for loading OCSP cache file is hardcoded as 24KB which is smaller than usual file size (150KB) and causes the loading always fail.
Tested with unit_ocsp_test manually, all cases passed and confirmed "OCSP cache file was successfully loaded" output in curl log.

SNOW-514869 loading OCSP cache file always fail

---

ci/test/test.sh
cpp/FileMetadataInitializer.cpp
cpp/FileTransferAgent.cpp
cpp/SnowflakeAzureClient.cpp
cpp/SnowflakeGCSClient.cpp
cpp/SnowflakeS3Client.cpp
cpp/StatementPutGet.cpp
lib/client.c
tests/test_simple_put.cpp

Simba ticket 00372396
When stage is created with "encryption = (type = 'SNOWFLAKE_SSE')", no encryption materials will be returned from server for put/get commands. ODBC driver doesn't support that and throws error.
Follow the implementation in JDBC, no encryption/decryption when either isClientSideEncrypted is off or encryption material is empty.

Support server side encryption (SNOWFLAKE_SSE)

---

cpp/FileTransferAgent.cpp
lib/platform.c
tests/test_simple_put.cpp

Command injection vulnerability found by Simba internally.
In libsnowflakeclient it's calling system() to delete temporary folder for the file compression during put command execution. The temporary folder is configurable by application (in ODBC, the application can set the path through PUT_TEMPDIR in connection string) so it could be used for command injection.
Check error when creating the temporary folder and confirm the existence before calling system() to delete.

fix command injection vulnerability with temp directory for put.

---

tests/test_unit_cipher_stream_buf.cpp
tests/test_unit_stream_splitter.cpp

Disable test using DEV_RANDOM on Linux as it could be blocked for a long time.

Disable DEV_RANDOM test on Linux

---

cpp/FileTransferAgent.cpp
cpp/util/SnowflakeCommon.cpp
lib/platform.c

Remove system() call and replace it with boost::filesystem::remove_all()

remove system() call to prevent command injection

---

CMakeLists.txt
cpp/SnowflakeAzureClient.cpp
cpp/SnowflakeS3Client.cpp
cpp/util/Proxy.cpp
deps/aws-sdk-cpp-1.3.50/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h
deps/aws-sdk-cpp-1.3.50/aws-cpp-sdk-core/include/aws/core/http/curl/CurlHttpClient.h
deps/aws-sdk-cpp-1.3.50/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
include/snowflake/IFileTransferAgent.hpp
include/snowflake/Proxy.hpp
scripts/build_azuresdk.bat
scripts/build_azuresdk.sh
tests/test_simple_put.cpp
tests/test_unit_proxy.cpp

Fix for ODBC proxy issue. So far the ODBC driver pass down proxy settings through environment variables, which would affect all connections in the same process. The customer who report this issue is using multi-threading to handling connections from different users, which would need different proxy setting for each connection.
Add proxy settings for aws/azure api also add proxy setting for file transfer so the odbc driver can use that to pass down proxy settings from connection string.
No test case added as libsnowflakeclient still use environment variables for connection, but test cases added on odbc side in this branch and passed on my local. https://github.com/snowflakedb/snowflake-odbc/tree/passdown-proxy-without-env
Will make ODBC PR from there when this PR is merged and tagged with …

Passdown proxy without env for file transfer

---

cpp/FileMetadata.hpp
cpp/FileMetadataInitializer.cpp
cpp/FileMetadataInitializer.hpp
cpp/SnowflakeAzureClient.cpp
cpp/SnowflakeGCSClient.cpp
cpp/SnowflakeS3Client.cpp
cpp/util/CompressionUtil.cpp
cpp/util/CompressionUtil.hpp
scripts/build_azuresdk.bat
scripts/build_azuresdk.sh
tests/test_simple_put.cpp
tests/test_unit_put_fast_fail.cpp

Simba ticket 00390901
Put command failed when file size is larger than 2GB.
Root cause: There are several places in libsnowflakeclient using long type variables for file size/offset, while long is 4 bytes on Windows and could cause data overflow when file size is larger than 2GB.

Put 2gb file

---

cpp/FileMetadata.hpp
cpp/FileMetadataInitializer.cpp
cpp/FileMetadataInitializer.hpp
cpp/FileTransferAgent.cpp
cpp/SnowflakeAzureClient.cpp
cpp/SnowflakeS3Client.cpp
include/snowflake/IFileTransferAgent.hpp
tests/test_simple_put.cpp
tests/test_unit_cred_renew.cpp

Simba ticket 00389874
The downloaded file could be corrupted when using aws multi-parts downloading and getting retry-able error from server side during the process. The root cause likely to be inside AWS SDK, while in the customer case they have multiple files to download and disable multi-parts downloading could get better performance.
Provide a new configuration to allow changing the threshold of multi-parts downloading  (was hardcoded to 5MB before) from application.
Will add a new connection/configuration parameter on ODBC side so we can pass the setting from there.
Eventually will upgrade AWS SDK to latest version (currently it's 1.3.50 which was released 4 years ago) and see if that can fix the issue.

Configurable get filesize threshold

---

scripts/build_openssl.bat
scripts/build_openssl.sh

Update openssl to 1.1.1q with the fix here: https://github.com/openssl/openssl/issues/18720 to solve the build issue on Mac.

Update openssl 1.1.1q

---

cpp/SnowflakeS3Client.cpp
cpp/util/ByteArrayStreamBuf.cpp
cpp/util/ByteArrayStreamBuf.hpp
tests/test_parallel_upload_download.cpp

Simba ticket 00389874
Fix the root cause of corrupted file with aws downloading
I thought it was aws sdk issue so made workaround in https://github.com/snowflakedb/libsnowflakeclient/pull/466
Tried fix it with updating aws sdk https://github.com/snowflakedb/libsnowflakeclient/pull/478 but the issue still there.
The root cause:
The driver provide response stream factory to aws sdk, and aws sdk expects it to return clean stream each time while the driver actually just return the same stream. When network retry occurs, the data from last failed attempt left over and make the data corrupted.
Add test cases to cover both single downloading and multi-parts downloading. It might not hit the network retry every time but could cover it sometime.
Tested locally to cut off network during the test …

fix downloading issue on network retry with aws

---

cpp/FileTransferAgent.cpp
cpp/FileTransferAgent.hpp
cpp/SnowflakeAzureClient.cpp
cpp/SnowflakeAzureClient.hpp
cpp/SnowflakeS3Client.cpp
cpp/SnowflakeS3Client.hpp
cpp/StatementPutGet.cpp
cpp/StatementPutGet.hpp
cpp/StorageClientFactory.cpp
cpp/util/SnowflakeCommon.cpp
include/snowflake/IStatementPutGet.hpp
include/snowflake/client.h
lib/chunk_downloader.c
lib/chunk_downloader.h
lib/client.c
lib/connection.c
lib/connection.h
lib/http_perform.c
tests/test_connect.c
tests/test_simple_put.cpp

Simba ticket 00402653
Support connection individual proxy settings for PHP connector.
Since PHP is using libsnowflakeclient we need to implement that in libsnowflakeclient first.

support proxy settings in connection attributes

---

cpp/lib/Authenticator.cpp
lib/authenticator.h
lib/client.c
lib/connection.c
tests/test_jwt.cpp

simba ticket 00404349
Key pair authentication doesn't work.
The bug itself is a simple typo and the problem is the test case didn't catch it. The reason is that setup_snowflake_connection() is called by all test cases to setup connection attributes from environments while password is set there. The jwt test cases were actually using user/password authentication to make the connection.
Unset password in test cases to ensure key pair auth is actually being used. Same test case issue on PHP side as well will make same fix there.

key pair auth bug fix

---

cpp/StatementPutGet.hpp

the override keyword caused build issue on Mac so remove it.

fix build issue on mac

---

deps/curl-7.84.0/lib/vtls/sf_ocsp.c
scripts/build_curl.bat
scripts/build_curl.sh
tests/unit_test_ocsp/test_ocsp.c

OCSP check is not using proxy being set through CURLOPT_PROXY and CURLOPT_NOPROXY so if connection individual proxy settings are set from there the OCSP check could fail.

bug fix: curl to use proxy for ocsp

---

cpp/SnowflakeGCSClient.cpp
cpp/SnowflakeGCSClient.hpp

for feature request: https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/91
The changes on libsnowflakeclient side to use down scoped token. Since libsnowflakeclient doesn't support GET/PUT for GCS by it's own no test cases added in this PR.
More changes and test cases are added on ODBC side here: https://github.com/snowflakedb/snowflake-odbc/tree/SNOW-480523-gcp-downscoped-token. Will make ODBC PR from there when this PR is merged and can be picked up from ODBC side.

[SNOW-480523] use gcs downscoped token for GET/PUT

---

cpp/util/SnowflakeCommon.cpp
deps/aws-sdk-cpp-1.3.50/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp
deps/azure-storage-cpplite-0.1.20/include/http/libcurl_http_client.h
deps/curl-7.88.1/lib/vtls/sf_ocsp.c
scripts/build_awssdk.bat
scripts/build_awssdk.sh
scripts/build_azuresdk.bat
scripts/build_azuresdk.sh

https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/294
ODBC driver sends empty Proxy-Authorization header to proxy server when no proxy username and password options in proxy settings which caused connection failure when using proxy.
The root cause is that when using proxy proxy username and password always been set without checking if they are empty.
Do the same fix [here](https://github.com/aws/aws-sdk-cpp/commit/59fe5b1b4d3cf9d26586a543376818e581f5aafc) for all the places need proxy settings.
No test case added as we don't have a proxy environment that doesn't need user/password authentication. But verify the fix with tcpdump as mentioned in the ticket, confirmed that
- without the fix Proxy-Authorization header was added with empty credentials
- with the fix …

Bug fix: only set proxy username and password options when specified

---

deps/curl-7.88.1/lib/vtls/sf_ocsp.c
tests/unit_test_ocsp/test_ocsp.c

https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/259
Encode Base64 OCSP Request data in URL for some corner cases that it might have characters that are not URL safe.
Unit test only as it's for for some corner cases that not easy to reproduce.

SNOW-761229 Bug fix: encoding ocsp request data in URL to avoid invalid URL issue

---

deps/curl-7.88.1/lib/vtls/sf_ocsp.c
scripts/build_curl.bat
scripts/build_curl.sh
tests/test_connect.c
tests/test_unit_oob.cpp

https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/371
The bug was just a typo but not caught by test cases since OCSP test is not run on Windows.
Add OCSP test case to run on all platforms.
Also disabled oob test due to this issue:
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/376

Bug fix: crash with OCSP validation

---

tests/test_unit_put_fast_fail.cpp

https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/340
Disable the flaky test case that takes too long time on jenkins run. It's still run on github though so should be able to catch any regression there.

SNOW-792806 disable flaky test on jenkins run

---

deps/boost-1.75.0/bootstrap.bat
scripts/build_arrow.bat
scripts/build_arrow_source.bat
scripts/build_azuresdk.bat
scripts/build_boost_source.bat
scripts/build_curl.bat
scripts/build_oob.bat
scripts/build_openssl.bat

The job has been failing when trying to compile Boost with Visual Studio 2022.
The fix for this was to add vc14 when calling the build.bat script.
Another issue was Boost was compiled for x86 and not for x64. The problem was with the environment variable platform. The value should be "x86" or "x64". However, when the script was trying to validate the platform the value was capitalized and the conditions failed. The fix is to update the condition with the correct value.
The fix worked in this test Jenkins job https://ci-dev-122.int.snowflakecomputing.com/job/LibSnowflakeClient-VSTest-Win64-VS14-Debug/11/

SNOW-867941 - Fix LibSnowflakeClient-Win64-VS14-Debug Jenkins job

---

tests/test_unit_oob.cpp

sdk issue 376. oob test was commented out due to certificate issue on telemetry endpoint. Enable it to check as the issue has been solved.

SNOW-819682 enable oob test

---

CMakeLists.txt

add build option of -Wno-error=deprecated-declarations to suppress the build error with boost header.

fix build issue with xcode14 on Mac

---

CMakeLists.txt
cpp/lib/QueryContextCache.cpp
cpp/lib/QueryContextCache.hpp
include/snowflake/client.h
lib/cJSON.c
lib/cJSON.h
lib/client.c
lib/query_context_cache.h
tests/CMakeLists.txt
tests/test_connect.c
tests/test_unit_query_context_cache.cpp

e2e test with queries mentioned in ODBC ticket (sdk issue 21) and the qcc content in log looks good.
[snowflake_20230906153320.txt](https://github.com/snowflakedb/libsnowflakeclient/files/12543069/snowflake_20230906153320.txt)
Currently the ODBC keep it's own implementation. Follow up ticket created to refactor implementation in libsnowflakeclient and reuse it in ODBC. https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/643

SNOW-871419 [HTAP] query context cache

---

include/snowflake/client.h
lib/chunk_downloader.c
lib/client.c
lib/client_int.h
lib/connection.c
lib/connection.h
lib/http_perform.c
tests/CMakeLists.txt
tests/test_connect.c
tests/test_unit_retry_context.c

sdk issue 550
Currently the new connection parameter SF_CON_INCLUDE_RETRY_CONTEXT controls both retryCount and retryReason as for libsnowflakeclient both of them are newly added while for other drivers retryCount already exist so the new connection parameter (like in ODBC) includeRetryReason only control retryReason.
@sfc-gh-igarish Please confirm whether to keep the current implementation or change to be inline with other drivers (always have retryCount and have a connection parameter to control retryReason)

SNOW-871471: [HTAP] add retry context in retry for query request

---

tests/test_unit_oob.cpp

After changing oob timeout from 100 seconds to 5 seconds in https://github.com/snowflakedb/libsnowflakeclient/pull/547
sometime oob test case fails on timeout. Treat that as expected result as we don't want to increase the timeout which could block customer application longer on oob sending.

fix flaky test case

---

tests/CMakeLists.txt
tests/test_stmt_functions.c

sdk issue 551
last query id for libsnowflakeclient
We have existing function snowflake_sfqid() returns last query id on statement level already while no test case cover it.
Add test case to ensure it works for both success and fail cases.

SNOW-871482: [HTAP] add test case for snowflake_sfqid

---

tests/test_unit_cred_renew.cpp

Unit test case hang on Jenkins on Linux aarch64 only. Temporarily comment out the flaky test cases.
sdk issue 658 created and will fix that in October and get the test cases back.

SNOW-918603: temporary comment out flaky test case on aarch64

---

ci/build/build.sh

Seems github reduced the diskspace for it's runners the debug build on Linux start to fail.
Remove some unnecessary files to save disk space.
The zip files was a pre-build version of arrow. Since currently we build arrow from source code on all platforms it's no use anymore. Anyone needs pre-build artifacts of arrow should get that from s3, like what ODBC is doing currently.
files in deps is not used after all dependencies building finished. The artifacts are in deps-build so deps can be deleted to save some space.

save diskspace on git

---

ci/build_linux.sh

Build fails again due to disk space issue.
Use workaround provided here https://github.com/actions/runner-images/issues/2840#issuecomment-790492173 to save more disk space.

save more disk space on github

---

include/snowflake/client.h
lib/chunk_downloader.c
lib/client.c
lib/client_int.h
lib/connection.c
lib/connection.h
lib/http_perform.c
tests/test_unit_retry_context.c
tests/test_unit_set_get_attributes.cpp

sdk issu 581
- add retry on http error code 429
- new retry strategy of jittered exponential backoff, max retry count of 7 and retry time of 300 seconds apply on login/authenticator/token requests
- add CLIENT_APP_ID, CLIENT_APP_VERSION in the header of login/authenticator/token requests

SNOW-878098: Retry Strategy

---

cpp/FileMetadataInitializer.cpp
cpp/FileMetadataInitializer.hpp
cpp/FileTransferAgent.cpp
include/snowflake/IStatementPutGet.hpp
tests/test_simple_put.cpp
tests/test_unit_file_metadata_init.cpp

libsnowflakeclient doesn't has the functionality for encoding conversion so it doesn't support Unicode characters by it's own.
Take the encoding conversion functionality from caller (.e.g ODBC driver) to support Unicode characters in file path for PUT/GET command.

SNOW-935778: Add support for unicode characters in file path in PUT/GET command

---

cpp/SnowflakeGCSClient.cpp
tests/test_unit_put_get_gcs.cpp

sdk issue 709
libsnowflakeclient itself doesn't support GCP so unit test case only. Will add functional test on ODBC side.

SNOW-945857: put with GCP to skip existing file

---

cpp/FileTransferAgent.cpp
cpp/SnowflakeAzureClient.cpp
cpp/crypto/CipherContext.cpp
cpp/lib/Authenticator.cpp
cpp/util/Proxy.cpp
include/snowflake/Simba_CRTFunctionSafe.h
include/snowflake/platform.h
lib/client.c
lib/connection.c
lib/http_perform.c
lib/logger.c
lib/platform.c

Microsoft made a list of banned CRT functions in their recent review feedback. We should use "safe" version (such as fopen_s for fopen) that they accept.

SNOW-945768: Addressing Banned functions in ODBC driver

---

ci/test_win.bat

Pip ugrade is required to install snowflake-connector-python but it breaks dependencies for other packages. awscli is installed again inside venv.

SNOW-954998: Install awscli in venv

---

include/snowflake/client.h
lib/client.c
lib/connection.c
lib/connection.h
lib/http_perform.c
tests/test_unit_retry_context.c
tests/test_unit_set_get_attributes.cpp

Add new connection attribute SF_CON_RETRY_TIMEOUT and SF_CON_MAX_RETRY for the new retry strategy.
SF_CON_RETRY_TIMEOUT: default to 300. 0 means unlimited. Can only be increased.
SF_CON_MAX_RETRY: default to 7. 0 means unlimited. Can only be increased.

SNOW-878098 retry strategy fix to match the design doc

---

cpp/FileMetadataInitializer.cpp
include/snowflake/IStatementPutGet.hpp

On Windows test on Jenkins, FindFirstFile() returns unexpected error ERROR_PATH_NOT_FOUND and break some test cases.
We only handle ERROR_FILE_NOT_FOUND before but since ERROR_PATH_NOT_FOUND also seems to be a reasonable error handle it same as ERROR_FILE_NOT_FOUND.

fix test case failures on jenkins Windows run

---

tests/test_unit_cred_renew.cpp
tests/test_unit_put_fast_fail.cpp

Turns out the fix we made in https://github.com/snowflakedb/libsnowflakeclient/pull/564 doesn't fix the hanging issue on Jenkins Linux run. Comment out the test cases again and will follow with sdk issue 658, 340

SNOW-918603: temporarily comment out hang test case on Jenkins Linux

---

cpp/FileTransferAgent.cpp
cpp/SnowflakeAzureClient.cpp
cpp/util/Proxy.cpp
include/snowflake/Simba_CRTFunctionSafe.h
include/snowflake/platform.h
lib/client.c
lib/logger.c
lib/platform.c

getenv and strerror are two banned functions, the replacement allocate memory that need to be released by caller.
(in part1 we only put stubs for the replacement but no effective change)
This is 2nd part of solution of issue #708, SNOW-945768: Addressing Banned functions in ODBC driver

replace ms-banned functions part2

---

cpp/FileTransferAgent.cpp
tests/test_unit_cred_renew.cpp
tests/test_unit_put_fast_fail.cpp

sdk issue 340, 658
Another attempt to fix the hanging issue on Linux Jenkins
Not sure if that's the root cause but using DEV_RANDOM would spend up to 2 seconds each time on my local and that could be a blocker on Jenkins if no enough entropy can be collected there. Change to use URANDOM to avoid possible blocker.
Also reduced unnecessary sleep to make the test case faster.

SNOW-918603: fix test hang issue on Jenkins Linux

---

CMakeLists.txt
cpp/lib/ClientQueryContextCache.cpp
cpp/lib/ClientQueryContextCache.hpp
cpp/lib/QueryContextCache.cpp
include/snowflake/QueryContextCache.hpp
include/snowflake/client.h
lib/client.c
lib/query_context_cache.h
tests/test_unit_query_context_cache.cpp

sdk issue 643
Make the QCC implementation reusable.
To reuse the implementation in ODBC, similar as what's been done in ClientQueryContextCache, make a subclass of QueryContextCache and use picojson instead of cJSON.

SNOW-910807: refactoring to reuse query context cache implementation in ODBC

---

scripts/build_arrow.bat

Fix the arrow version for artifacts uploading since the package on S3 for debug version seems broken and we need to re-upload.

SNOW-937196: make correction on arrow version for uploading

---

tests/CMakeLists.txt
tests/test_lob.c

sdk issue 751
This PR is for testing only. make it draft and won't merge for now.
Need to increase MAX_LOB_SIZE definition to test on Snowflake side.
The test case could be merged when the feature is stable and can be released, but at that time we might need to reduce the test cases (especially the number of sizes being tested) as currently it might take too much time to run due to the large data size.

SNOW-968730: Increased max LOB size complete testing

---

lib/connection.c

MSFT code scanning finds this bug although it does not likely happen because 256 extra bytes are allocated. Fixit anyway.

SNOW-983107: libsnowflakeclient - possible out of bounds mem access

---

scripts/utils.bat

No luck on making a general upper converter but I think set with upper case values would be good enough for now.

set CLOUD_PROVIDER with upper case to fix jenkins test issue

---

tests/test_large_result_set.c
tests/utils/test_setup.c

use uuid for test database name to increase randomness
disable OCSP validation for result chunk downloading on GCP to around issue for now. We might want to support FAIL_OPEN in libsnowflakeclient.

SNOW-1048186 test failures on Jenkins

---

lib/platform.c
tests/test_unit_proxy.cpp

getenv_s() returns 0 (success) for variables not set.
remove skip condition in test case to ensure the test case never be skipped unexpectedly.

SNOW-1526802: sf_getenv_s on Windows with variable not set

---

.github/workflows/jira_issue.yml

There is no code change here, just GH Action is modified.
`create-issue` GH Action fails, after creating the Jira ticket, it is not able to update the autogenerated Jira id back into the GH Issue's title:
```
fatal     HttpError: Resource not accessible by integration
```
Looks to be the same as `SNOW-1334777` so applying the same solution.

SNOW-1795105 fix permissions for create-issue

---

.github/workflows/build-test.yml
ci/build/build.sh
ci/build_win.bat
scripts/_init.sh
scripts/utils.bat
scripts/utils.sh

Uses github action caches to speed up the builds:
- Creates a cache associated with a commit on master branch (when built on master)
- Restores the cache on build step in pull requests resulting in faster builds (19m down to 4.5m on Release Linux build)

SNOW-1825584: Cache deps to speed up the builds

---

README.rst
cpp/FileTransferAgent.cpp
deps/curl/lib/vtls/sf_ocsp.c
include/snowflake/QueryContextCache.hpp
lib/client.c
lib/results.c
scripts/_init.sh
scripts/build_arrow.bat
scripts/build_arrow_source.bat
scripts/build_awssdk.bat
scripts/build_azuresdk.bat
scripts/build_boost_source.bat
scripts/build_cmocka.bat
scripts/build_curl.bat
scripts/build_dependencies.bat
scripts/build_dependencies.sh
scripts/build_libsnowflakeclient.bat
scripts/build_oob.bat
scripts/build_oob.sh
scripts/build_openssl.bat
scripts/build_openssl.sh
scripts/build_picojson.bat
scripts/build_zlib.bat
scripts/run_tests.sh
tests/test_column_fetch.c
tests/test_perf_string_reads_and_writes.c
tests/test_unit_logger.c
tests/test_unit_put_fast_fail.cpp

teamwork issue 534
Update build/test scripts and instruction.
Tested on Windows VS14/VS17, Linux x86 Centos7+gcc8.3, Linux arm64 Ubuntu24.04+gcc13.2, MacOS13+Xcode14.2
The major changes are:
- Fixed warnings in source code with higher version of compiler
- Fixed issues with environment variable settings in build script (e.g. setting `curdir` could break build with VS14, setting `AR` in `build_oob.sh` could break curl build afterwards with Xcode14)
- Fix test failures
- Update build/test instruction

SNOW-864140 update build scripts instruction

---

cpp/lib/ArrowChunkIterator.cpp

Fix implicit-const-int-float-conversion warnings

SNOW-1865097 use explicit casts to compare doubles against integer limits

---

.github/workflows/build-test.yml

Start to get build error on Linux:
https://github.com/snowflakedb/libsnowflakeclient/actions/runs/12637669839/job/35212346592?pr=757
```
Run actions/setup-python@v5
Installed versions
Version 3.7 was not found in the local cache
Error: The version '3.7' with architecture 'x64' was not found for Ubuntu 24.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
Update python version from 3.7 to 3.13 to fix the issue

NO-SNOW: Update python version to fix build issue

---

tests/test_crud.c

teamwork issue 1214
temporarily disable length check on azure/gcp in case it's a server issue need some time to be fixed and would be a blocker for 2.0 release.

SNOW-1899737: temporarily disable length check in test_crud on azure/gcp

---

cpp/lib/BindUploader.cpp
include/snowflake/platform.h

UNUSED already defined in ODBC cased definition conflict.

SNOW-710476: fix build issue with ODBC

---

tests/test_bind_params.c
tests/test_column_fetch.c
tests/test_unit_connect_parameters.c
tests/test_unit_pat.c
tests/utils/test_setup.h

1. Remove UNUSED macro from test_setup.h.
2. Replace UNUSED usages with SF_UNUSED

remove UNUSED macro from tests, use SF_UNUSED instead

---

.github/workflows/build-test.yml

I takes ~30 minutes for all tests to pass (if no tests fail, and need to be rerun). I takes another 40+ to do code coverage. Because code coverage depends on regular tests the whole pipeline takes at least 1h10min. This should cut CI time in half.

SNOW-1908809: Speed up gh actions

---

lib/client.c
tests/test_unit_logger.c

Fix for SNOW-981602 Implement Easy Logging using a config file. Add initialization for clientconfig and add test case

SNOW-981602: Fix missing clientconfig initialization, add test case

---

cpp/util/SnowflakeCommon.cpp

Master branch fails to compile (on vs2022) due to missing import and minor compiler version upgrade.
[logs](https://productionresultssa9.blob.core.windows.net/actions-results/a4986b37-268f-4a80-b021-3248f88f0424/workflow-job-run-18a4ea19-b0c5-57fc-dc31-e67404c6b25e/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-03-04T14%3A35%3A34Z&sig=n2ad2x%2BXafmSKuP7axfPBa8xda1iB0XVjAba%2BpJITIY%3D&ske=2025-03-05T01%3A02%3A18Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-03-04T13%3A02%3A18Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-01-05&sp=r&spr=https&sr=b&st=2025-03-04T14%3A25%3A29Z&sv=2025-01-05)

NO-SNOW: Add missing chrono import

---

cpp/lib/Authenticator.cpp

The variable m_socket_desc_web_client is not initialized, and if browser timeout or other exceptions occur when starting it can lead to unpredictable results.

SNOW-2004104 variable initialization

---

.github/workflows/build-test.yml
.github/workflows/code-quality.yml

Build caches get wiped after a week of not being used. When development is slow the caches can get wiped - this causes:
- slow builds
- code quality fails since Extra Warnings compares its result with master

NO-SNOW: Refresh build caches by running actions each week
