snowflakedb/libsnowflakeclient

- include/snowflake/client.h
- include/snowflake/platform.h
- lib/client.c
- lib/connection.c
- lib/logger.c
- lib/platform.c
- tests/CMakeLists.txt
- tests/test_unit_connect_parameters.c
- tests/test_unit_logger.c
- Added region parameter
- Construct a hostname from account and region if not specified.
> Region support

- appveyor.yml
Fixing pip upgrade failure on Windows.
> use pip upgrade

- cpp/SnowflakeS3Client.cpp
- cpp/crypto/Cryptor.cpp
- cpp/util/StreamSplitter.cpp
- cpp/util/StreamSplitter.hpp
- cpp/util/ThreadPool.hpp
- tests/CMakeLists.txt
- tests/test_parallel_upload.cpp
- tests/test_unit_stream_splitter.cpp
- tests/test_unit_thread_pool.cpp
This branch originally aims at fixing the bug. However, so far I have not figured out why. I might need to  implement GET to further debug. Here is some improvements I want to check in. Also, this disable the intermittent failure tests.
> Minor improvement

- CMakeLists.txt
- cpp/EncryptionProvider.cpp
- cpp/EncryptionProvider.hpp
- cpp/FileMetadataInitializer.cpp
- cpp/FileMetadataInitializer.hpp
- cpp/FileTransferAgent.cpp
- cpp/FileTransferAgent.hpp
- cpp/FileTransferExecutionResult.cpp
- cpp/FileTransferExecutionResult.hpp
- cpp/IStorageClient.hpp
- cpp/PutGetParseResponse.cpp
- cpp/PutGetParseResponse.hpp
- cpp/RemoteStorageRequestOutcome.hpp
- cpp/SnowflakeS3Client.cpp
- cpp/SnowflakeS3Client.hpp
- cpp/crypto/CipherStreamBuf.cpp
- cpp/crypto/CipherStreamBuf.hpp
- cpp/util/ByteArrayStreamBuf.cpp
- cpp/util/ByteArrayStreamBuf.hpp
- cpp/util/ThreadPool.hpp
- include/snowflake/logger.h
- lib/client.c
- lib/client_int.h
- tests/CMakeLists.txt
- tests/test_parallel_upload_download.cpp
- tests/test_unit_cipher_stream_buf.cpp
- tests/test_unit_cred_renew.cpp
- tests/test_unit_file_metadata_init.cpp
- tests/test_unit_stream_splitter.cpp
- tests/test_unit_thread_pool.cpp
Support parallel download and multi part download
TODO:
Handle token renew.
> Get command

- CMakeLists.txt
- cpp/FileMetadataInitializer.cpp
- cpp/FileTransferAgent.cpp
- cpp/IFileTransferAgent.cpp
- cpp/SnowflakeS3Client.cpp
- cpp/StorageClientFactory.cpp
- cpp/crypto/CryptoTypes.hpp
- cpp/logger/ISFLogger.cpp
- cpp/logger/SFAwsLogger.cpp
- cpp/logger/SFLogger.cpp
- cpp/logger/SFLogger.hpp
- include/snowflake/IFileTransferAgent.hpp
- include/snowflake/ISFLogger.hpp
Mainly for ODBC to inject logger
> Improve logging interface so that external logger can be injected

- .travis.yml
> Fixed code coverage

- cpp/FileTransferAgent.cpp
- cpp/FileTransferAgent.hpp
- cpp/IFileTransferAgent.cpp
- cpp/SnowflakeS3Client.cpp
- cpp/SnowflakeS3Client.hpp
- cpp/StorageClientFactory.cpp
- cpp/StorageClientFactory.hpp
- include/snowflake/IFileTransferAgent.hpp
Add interface so that ODBC can pass cabundfile config to C++ API.
> Add config interface

- cpp/StatementPutGet.cpp
- lib/cJSON.c
- lib/cJSON.h
- lib/chunk_downloader.c
- lib/client.c
- lib/connection.c
- lib/results.c
Change cJSON namespace to avoid linking conflict.
> Change cJSON namespace

- include/snowflake/client.h
- lib/client.c
- lib/client_int.h
- lib/connection.c
Adding token for direct request to GS.
> Smirzaei sp branch

- cpp/SnowflakeS3Client.cpp
pasted CI tests and ready to merge
> force S3Client to use virtual addressing style

- lib/platform.c
> Change local timestamp to UTC timestamp

- CMakeLists.txt
- cpp/FileCompressionType.cpp
- cpp/SnowflakeTransferException.cpp
- cpp/crypto/Cryptor.cpp
- cpp/lib/Connection.cpp
- Enabled -Werror to cause error on warning
- Fixed more warnings for clang
> Warnings are error

- CMakeLists.txt
- lib/arraylist.c
- lib/client.c
- scripts/books_to_csv.py
- scripts/create_schema.py
- scripts/drop_schema.py
- scripts/run_travis.sh
- scripts/setup_test_data.py
- scripts/sf_test_utils.py
- tests/CMakeLists.txt
- tests/test_perf_column_evaluation.c
- tests/test_perf_string_reads_and_writes.c
- tests/test_perf_type_conversion.c
- tests/utils/test_setup.c
- tests/utils/test_setup.h
Added first set of performance tests along with the necessary test infrastructure to support the performance tests as well as populate test data into the test deployment. Fixed error due to passing in NULL arraylist. Implemented total_row_index in C API as well to support performance tests.
> Added first set of performance tests 

- lib/client.c
- lib/client_int.h
- lib/connection.c
- lib/uuid4.c
Implemented a request GUID that is unique per request to Snowflake
> Request GUID

- scripts/run_tests.sh
Updated test runner script to be able to skip env args update
> Update test runner script

- README.rst
Added documentation on how to enable proxy support in libsnowflakeclient
> Added proxy documentation

- include/snowflake/client.h
- lib/results.c
- tests/test_crud.c
Added description idx (indexed at 1) and updated test cases to reflect changes.
> Added description idx

- lib/client.c
- lib/client_int.h
- tests/CMakeLists.txt
- tests/test_native_timestamp.c
Fixed DATE type to SF_TIMESTAMP struct conversion bug. Added a test case to check the native timestamp type column conversion from all Snowflake time/date types.
> Fixed DATE type to SF_TIMESTAMP struct Conversion bug

- deps/curl-7.58.0/lib/vtls/sf_ocsp.c
This updates sf_ocsp.c with the ODBC's one including a couple of bug fixes.
> updated Curl OCSP code

- .travis.yml
- CMakeLists.txt
- include/snowflake/client.h
- lib/chunk_downloader.c
- lib/chunk_downloader.h
- lib/client.c
- lib/client_int.h
- lib/connection.c
- lib/connection.h
- lib/http_perform.c
- lib/mock_http_perform.h
- mock_parameters.json
- scripts/build_libsnowflakeclient.sh
- scripts/run_travis.sh
- tests/CMakeLists.txt
- tests/mock/test_mock_service_name.c
- tests/unit/mock/snowflake_mock.h
- tests/utils/mock_endpoints.h
- tests/utils/mock_setup.c
- tests/utils/mock_setup.h
Added support for service name as well as completed a refactoring of request headers. A mock test framework was also added to verify that service name works.
> Service name

- deps/zlib-1.2.11/.gitignore
- deps/zlib-1.2.11/Makefile
- scripts/build_zlib.sh
Remove generated files
distclean zlib before configure.
> Remove generated file Makefile 

- cpp/FileTransferAgent.cpp
- include/snowflake/platform.h
- lib/platform.c
- scripts/build_awssdk.bat
Create a uuid string append to the temp dir to create a unique temp directory.
> Append UUID string to the tmp dir to create unique dir

- lib/client.c
- tests/test_column_fetch.c
Fixed issues with returning time since epoch for TIMESTAMP_LTZ and TIMESTAMP_TZ
> Timestamp bugs

- include/snowflake/client.h
- lib/results.c
- tests/test_null.c
Added support for binding NULL input parameters when you don't know that the C type of that column is.
> NULL input support

- cpp/util/ThreadPool.hpp
- tests/test_connect_negative.c
https://snowflakecomputing.atlassian.net/browse/SNOW-85722
> snow-85722 Perform check for thread index allocation and free index

- .travis.yml
- lib/client.c
- lib/client_int.h
- lib/connection.c
- lib/constants.h
Updated the USER AGENT header to reflect new format. Fixed issues with Travis migrating to Ubuntu 16.04 as standard image
> User agent

- cpp/SnowflakeAzureClient.cpp
- cpp/SnowflakeS3Client.cpp
- cpp/SnowflakeTransferException.cpp
- cpp/crypto/CryptoTypes.hpp
- cpp/crypto/Cryptor.cpp
- cpp/util/Base64.hpp
- include/snowflake/Simba_CRTFunctionSafe.h
- include/snowflake/client.h
- include/snowflake/platform.h
- lib/cJSON.c
- lib/cJSON.h
- lib/chunk_downloader.c
- lib/client.c
- lib/client_int.h
- lib/connection.c
- lib/error.c
- lib/http_perform.c
- lib/platform.c
- lib/results.c
This is mainly Simba's Fix with some change on:
1. inline issue
2. vsnprintf() usage
> Simba GitHub pr

- cpp/FileMetadataInitializer.cpp
- cpp/FileMetadataInitializer.hpp
- cpp/SnowflakeAzureClient.cpp
- cpp/SnowflakeS3Client.cpp
- tests/test_unit_cred_renew.cpp
* upload threshold is 64MB;
* download threshold is 5MB;
> SNOW-132027 Change PUT command threshold to be consistent with other drivers

- .gitignore
- ci/build/build.sh
- ci/dev/Dockerfile
- ci/dev/README.rst
- ci/dev/docker_init.sh
- ci/dev/entrypoint.sh
- ci/dev/start.sh
- scripts/_init.sh
- scripts/build_libsnowflakeclient.sh
- scripts/utils.sh
- (DONE) Added dev container. Similar to ODBC.
- (WIP) Update Curl and add OOB
> Additional changes.

- scripts/build_oob.bat
The main fails to upload oob zip.
> upload oob zip

- CMakeLists.txt
- cpp/FileMetadata.hpp
- cpp/FileMetadataInitializer.cpp
- cpp/FileMetadataInitializer.hpp
- cpp/FileTransferAgent.cpp
- cpp/FileTransferAgent.hpp
- cpp/IStorageClient.hpp
- cpp/SnowflakeGCSClient.cpp
- cpp/SnowflakeGCSClient.hpp
- cpp/StorageClientFactory.cpp
- cpp/StorageClientFactory.hpp
- include/snowflake/IFileTransferAgent.hpp
- include/snowflake/IStatementPutGet.hpp
- include/snowflake/PutGetParseResponse.hpp
1. Support PUT/GET on GCP for ODBC Driver
2. Support Bulk parameter array binding for ODBC Driver
> Simba changes for PUT/GET on GCP and bulk parameter array binding

- cpp/SnowflakeAzureClient.cpp
delete the azure client to free resources.
>  SNOW-168900: fix resource leak for putget on azure

- deps/oob-1.0.2/jsonutil.c
- deps/oob-1.0.2/jsonutil.h
- deps/oob-1.0.2/oobtelemetry.h
- tests/test_unit_oob.cpp
DSN Test result: 
```
[{
"Created_On":	"2020-07-13 20:47:44",
"Name":	"ConnectionDSNConfig",
"SchemaVersion":	1,
"Tags":	{
"UUID":	"69d11590-3401-4228-a61c-7583b81ed688",
"connectionString":	"snowflake.local.snowflakecomputing.com:443/session/v1/login-request?requestId=c4d53986-ee7a-4f01-9fac-2604653e9c41&request_guid=abbab0e5-5c77-4102-9d29-d44efde6a050&databaseName=testdb&schemaName=testschema&warehouse=regress",
"ctx_account":	"sfctest0",
"ctx_port":	"443",
"ctx_protocol":	"https",
"ctx_user":	"snowman",
"driver":	"ODBC",
"version":	"99.0.0",
"hostOs":	"Linux",
"telemetryServerDeployment":	"dev"
},
"Type":	"Log",
"UUID":	"69d11590-3401-4228-a61c-7583b81ed688",
"Urgent":	false,
"Value":	{
"DSN":	{
"SERVER":	"snowflake.local.snowflakecomputing.com",
"PORT":	"443",
"ACCOUNT": …
```
> SNOW-169969 Add DSN and Connection Parameters to ODBC OOB

- include/snowflake/Statement.hpp
- include/snowflake/client.h
- lib/client.c
- lib/http_perform.c
- lib/results.c
- lib/results.h
- tests/CMakeLists.txt
- tests/test_stats.c
Description
See snowflakedb/snowflake#11348 for how response changed.
Testing
test_stats passed but still can't enable until changes go out in GS (see screenshot)
> SNOW-57187 Refactor row metadata in response (libsnowflakeclient changes)

- cpp/SnowflakeGCSClient.cpp
- scripts/build_openssl.bat
- scripts/build_openssl.sh
- scripts/build_uuid.sh
upgrade openssl to 1.1.1g
upgrade util-linux to 2.36
> Upgrade dependencies for security vulnerabilities

- cpp/SnowflakeGCSClient.cpp
- scripts/build_openssl.bat
- scripts/build_openssl.sh
- scripts/build_uuid.sh
Reverts snowflakedb/libsnowflakeclient#233
> Revert "Upgrade dependencies for security vulnerabilities"

- scripts/build_curl.bat
- scripts/build_curl.sh
Update curl patch version specific to snowflake specific changes in curl.
> SNOW 204166 update curl version for telemetry update

- cpp/FileTransferAgent.cpp
- tests/test_unit_cred_renew.cpp
File upload and download are not exception safe. Exception could be thrown on renew token, encryption, compression, file I/O and upload/download for gcp through REST request.
When do file transfer in parallel with multiple threads (small files), exception can't be caught on main thread and could crash the application.
1. Catch exception in threads for upload/download small files.
2. Add test cases
3. Fix missing default value of fast fail (false)
> SNOW-218025 catch exception in threads for upload and download

- cpp/SnowflakeGCSClient.cpp
- scripts/build_openssl.bat
- scripts/build_openssl.sh
Upgrade openssl to 1.1.1i as request from MSFT
> Upgrade openssl to 1.1.1i

- CMakeLists.txt
- cpp/logger/SFLogger.cpp
- cpp/logger/SFLogger.hpp
- cpp/logger/SecretDetector.cpp
- cpp/logger/SecretDetector.hpp
- include/snowflake/logger.h
- lib/logger.c
- tests/CMakeLists.txt
- tests/test_unit_logger.c
> Add SecretDetector to mask secret information in log

- cpp/logger/SFLogger.cpp
Fix build error on Mac introduced in https://github.com/snowflakedb/libsnowflakeclient/pull/260
> Fix build error on Mac for log credential check

- scripts/_init.sh
Updates min supported version to 10.13
> Update MACOSX_VERSION_MIN supported to 10.13

- CMakeLists.txt
- cpp/logger/SFLogger.hpp
- cpp/logger/SecretDetector.cpp
- cpp/logger/SecretDetector.hpp
- include/snowflake/ISFLogger.hpp
- scripts/build_arrow.bat
- scripts/build_arrow.sh
replace std::regex with boost::regex
> logging performance improvement

- scripts/build_openssl.sh
Makes it compatible with ARM builds
> Make openssl build compatible with ARM builds

- CMakeLists.txt
- ci/build/build.sh
- lib/connection.c
- lib/http_perform.c
- scripts/_init.sh
* Add a flag to disable certain pieces of code for XP
* Add gcc82 to list of compilers that can be picked up
* Macro the pieces that XP does not use with the defined flag
Testing
Changes are in the build scripts, The existing Tests should pass.
> SNOW-301717 Libsnowflakeclient build for XP

- cpp/SnowflakeS3Client.cpp
- cpp/logger/SFAwsLogger.cpp
- cpp/logger/SFAwsLogger.hpp
Fix for simba ticket 00313852.
> Fix crash issue with aws logging when using multiple trheads.

- .github/workflows/build-test.yml
- scripts/build_openssl.bat
- scripts/build_openssl.sh
Upgrade to openssl 1.1.1l as MSFT requested.
> move to openssl 1.1.1l

- deps/curl-7.78.0/lib/vtls/sf_cJSON.c
- deps/curl-7.78.0/lib/vtls/sf_cJSON.h
- lib/cJSON.c
- lib/cJSON.h
Update cJSON in curl (was 7.1.4) and libsnowflakeclient (was 7.1.12) to 7.1.15
Compared existing code with original cJSON code to ensure all custom changes are applied.
Also compared changes in original code to confirm any further custom change is needed there.
Make separate commit for custom changes so we can reference to it when upgrading to a new version next time.
Remember to bump up minor version of both curl and libsnowflakeclient in the next release.
> Update cJSON to 1.7.15

- .github/workflows/jira_close.yml
- .github/workflows/jira_issue.yml
Committed via https://github.com/asottile/all-repos
> SNOW-499170 Bringing GH actions up-to-date with Python connector's

- scripts/build_awssdk.bat
- scripts/build_awssdk.sh
bump up aws version to update build artifacts
> bump up aws version

- CMakeLists.txt
- cpp/lib/Authenticator.cpp
- cpp/lib/Authenticator.hpp
- include/snowflake/client.h
- lib/authenticator.h
- lib/chunk_downloader.c
- lib/client.c
- lib/connection.c
- lib/connection.h
- lib/error.h
- lib/http_perform.c
- tests/CMakeLists.txt
- tests/test_jwt.cpp
Simba ticket 00389231
Add support for key pair authentication for PHP. Since PHP is using libsnowflakeclient the feature needs to be added here.
> Keypair auth support

- ci/build_win.bat
- scripts/arrow.mk
- scripts/utils.bat
- scripts/utils.sh
Revert to Unblock the release.
> Revert "Move References to New S3 Buckets in sfc-dev2"

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Adding Bug and Feature teamples as we have it in other drivers such as JDBC repo.
> add bug and feature templates

- cpp/SnowflakeS3Client.cpp
- cpp/lib/ArrowChunkIterator.cpp
Use https://github.com/x509cert/banned to check all banned functions and replace them with safe ones.
> remove banned functions

- CMakeLists.txt
- README.rst
- scripts/build_libsnowflakeclient.sh
- scripts/gen_coverage_report.sh
- tests/CMakeLists.txt
- tests/test_unit_put_get_gcs.cpp
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/152
Add script to generate code coverage report on Linux
Note down steps in Readme
Add test case for GCS so the coverage number increased to 81%
> generate code coverage report

- scripts/build_azuresdk.sh
- scripts/build_dependencies.sh
Get fixes from this PR https://github.com/snowflakedb/libsnowflakeclient/pull/496
Currently the build scripts work for Snowflake build on github and jenkins but could fail for someone build from scratch with higher compiler version.
> minor fixes for build scripts

- cpp/crypto/Cryptor.cpp
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/253
Following the guidance here: https://www.openssl.org/docs/man3.0/man7/OPENSSL_NO_DEPRECATED.html
build libsnowflakeclient with following definition and fix all build errors.(OPENSSL_API_COMPAT set to the version number of 1.1.1q to disable all deprecated functions in previous versions)
OPENSSL_API_COMPAT=0x1010111fL
OPENSSL_NO_DEPRECATED
> SNOW-760226 Bug fix: remove deprecated openssl function calls

- deps/azure-storage-cpplite-0.1.20/include/http/libcurl_http_client.h
Document the expected behavior details and make the logic more clear based on the discussion here
https://github.com/snowflakedb/pdo_snowflake/pull/321
> Code hygiene to make the logic more clear with detailed comment

- README.rst
Issue 543: https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/543
> SNOW-870361: Add Codecov badge to README.rst

- tests/test_simple_put.cpp
Fix the build issue on Mac with newly added test case.
> fix build issue on Mac

- scripts/_init.bat
- scripts/build_arrow.bat
sdk issue 697/720
having performance issue with the arrow library built from source code.
Revert to use old one (pre-build binary) which only available on Windows.
This is temporary approach so we can fix the customer issue in Jan release.
Will update arrow to newer version (targeting 14.x but might be changed later) soon (Feb or Mar) and confirm no performance issue introduced before release.
> SNOW-937196: revert to pre-build arrow on Windows

- ci/_init.sh
- ci/build_linux.sh
- ci/image/Dockerfile.libsnowflakeclient-centos7-default-build
- ci/image/build.sh
- ci/test_linux.sh
- tests/CMakeLists.txt
- tests/test_connect_negative.c
arrow 15.x needs to be built with c++17 standard and need gcc update.
> SNOW-983098: update centos7 docker image with gcc8.3

- ci/test_win.bat
> fix path for drop schema

- lib/client.c
- lib/memory.c
- lib/platform.c
- lib/uuid4.c
> SNOW-1319983: fix issue/banned functions found in security review

- tests/CMakeLists.txt
- tests/unit_test_ocsp/CMakeLists.txt
- tests/unit_test_ocsp/test_ocsp.c
> SNOW-1063850: enable OCSP test case

- .github/workflows/build-test.yml
- scripts/build_arrow_source.sh
- scripts/build_curl.sh
- scripts/build_oob.sh
- tests/unit_test_ocsp/CMakeLists.txt
> SNOW-1065141: enable test on mac

- cpp/SnowflakeS3Client.cpp
- tests/test_unit_put_get_fips.cpp
> SNOW-1446336: Use S3 regional url domain base on region name

- lib/client.c
- lib/logger.c
- tests/test_large_result_set.c
> SNOW-1367439: delay log folder creation to when logging really needed

- CMakeLists.txt
- cpp/util/CurlDesc.cpp
- cpp/util/CurlDescPool.cpp
- cpp/util/SFURL.cpp
- include/snowflake/BaseClasses.hpp
- include/snowflake/CurlDesc.hpp
- include/snowflake/CurlDescPool.hpp
- include/snowflake/SFURL.hpp
- lib/chunk_downloader.c
- lib/connection.c
- lib/curl_desc_pool.h
- scripts/gen_coverage_report.sh
- tests/CMakeLists.txt
- tests/test_unit_sfurl.cpp
> SNOW-1048186: Reuse curl connection to improve performance

- tests/test_parallel_upload_download.cpp
- tests/test_simple_put.cpp
- tests/utils/test_setup.c
- tests/utils/test_setup.h
> SNOW-1437443: use random db to allow test in parallel

- tests/test_connect_negative.c
Fix intermittent test failure on testing chunk downloading timeout
> Ignore query timeout when testing downlonding timeout

- CMakeLists.txt
- README.rst
- scripts/build_libsnowflakeclient.bat
Upgrade cmake to latest version on available on our environments(3.17)
- Change cmake version
- Migrate to modern way of handling MSVC Runtime Library (https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html)
> SNOW-1789728: Upgrade cmake version

- .github/workflows/build-test.yml
- ci/build/build.sh
- ci/build_win.bat
- scripts/_init.sh
- scripts/utils.bat
- scripts/utils.sh
In this PR:
- We cache deps built on master
- We use cached deps on pull requests to speed up build times
> SNOW-1825584: Cache deps to speed up the builds

- cpp/SnowflakeGCSClient.cpp
- cpp/SnowflakeGCSClient.hpp
- cpp/SnowflakeS3Client.cpp
- cpp/StatementPutGet.cpp
- include/snowflake/PutGetParseResponse.hpp
- lib/client.c
- lib/client_int.h
- tests/test_unit_put_get_gcs.cpp
> SNOW-1789750: support GCS regional endpoint

- scripts/build_picojson.bat
> SNOW-1858503 fix libsnowflakeclient Windows builds on Actions

- cpp/FileTransferAgent.cpp
- cpp/lib/ResultSetPutGet.cpp
- cpp/lib/ResultSetPutGet.hpp
- lib/client.c
- lib/results.c
- lib/results.h
- tests/test_column_fetch.c
> SNOW-1871835: fix for omitted length in query response

- lib/results.c
- tests/test_column_fetch.c
previous fix in PR #814 breaks behavior for fixed length data types like date, time.  Fix that and add test case to cover all types.
> SNOW-1871835: bug fix for omitted length with bundle 2024_08

- cpp/linux/CacheFile.cpp
- tests/test_unit_secure_storage_linux.cpp
Security validation PR: https://github.com/snowflakedb/security_reviews/pull/6537/files/ddaac47323c8d4787574b5386f28522927801e1c#diff-b2dfb48cf34a96b21f1f876dfaed445227bcd18941859bfcceeb638e32cec686
> SNOW-1825787: Security validation fixes

- cpp/util/CurlDescPool.cpp
SNOW-1991254 curl descriptor cleanup in OCSP test mode
> SNOW-1991254 curl descriptor cleanup in OCSP test mode

- cpp/util/CurlDescPool.cpp
SNOW-1991254 revert curl descriptor cleanup in OCSP test mode
> SNOW-1991254 revert curl descriptor cleanup in OCSP test mode

- .github/workflows/build-test.yml
- ci/build_linux.sh
- cmake/flags.cmake
- lib/client.c
- lib/connection.c
- tests/CMakeLists.txt
- tests/mock/test_mock_mfa_token_caching.c
- Enable MFA Token cache
- Add mock tests pipeline on CI
> SNOW-1705754: Enable MFA Token cache

- cpp/logger/SecretDetector.cpp
- cpp/logger/SecretDetector.hpp
- lib/connection.c
- tests/test_unit_logger.c
- tests/test_unit_retry_context.c
SNOW-1729580: Remove encryption storage information in logs
SNOW-1739682: Remove retry on 400
> SNOW-1729580 + SNOW-1739682 Remove encryption storage information in logs, remove retry on 400 

- cpp/AWSUtils.cpp
- include/snowflake/AWSUtils.hpp
- lib/client.c
teamwork issue 1209. Fix hanging issue with put/get test case in PHP driver, when trying to update libsfclient to 2.2.0
> SNOW-1887475: fix hanging issue in PHP when calling ShutdownAPI() for aws sdk

- cpp/AwsAttestation.cpp
- cpp/AzureAttestation.cpp
- cpp/WifAttestation.cpp
- include/snowflake/WifAttestation.hpp
- tests/test_create_wif_attestation.cpp
- tests/test_manual_wif.cpp
> SNOW-2061784 fixes for ODBC

- cpp/AwsAttestation.cpp
- cpp/AzureAttestation.cpp
- cpp/AzureAttestation.hpp
- cpp/WifAttestation.cpp
- include/snowflake/WifAttestation.hpp
- tests/test_create_wif_attestation.cpp
- tests/test_manual_wif.cpp
> SNOW-2061784 fixes for WIF in ODBC

- cpp/AWSUtils.cpp
- cpp/AwsAttestation.cpp
- cpp/SnowflakeS3Client.cpp
- cpp/SnowflakeS3Client.hpp
- include/snowflake/AWSUtils.hpp
- lib/client.c
> SNOW-2061784 fixes for Aws initialization

- cpp/AWSUtils.cpp
- cpp/AwsAttestation.cpp
- cpp/SnowflakeS3Client.cpp
- cpp/SnowflakeS3Client.hpp
- include/snowflake/AWSUtils.hpp
- lib/client.c
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/1265
Reverts snowflakedb/libsnowflakeclient#893
> SNOW-2111927: Revert "SNOW-2061784 fixes for Aws initialization"

- cpp/util/Proxy.cpp
- tests/test_unit_proxy.cpp
SNOW-2285315: Fix NO_PROXY character limit
> SNOW-2295402: Fix NO_PROXY character limit

- tests/test_unit_connect_parameters.c
SNOW-2316570-disable-debug-logs
> SNOW-2316570-disable-debug-logs
